export type LocalFile={name:string;file:File};
export async function readEntries(entries:any[],prefix=''):Promise<LocalFile[]>{const out:LocalFile[]=[];for(const entry of entries){if(entry.isFile)out.push({name:prefix+entry.name,file:await new Promise<File>((r,j)=>entry.file(r,j))});else{const reader=entry.createReader();for(;;){const batch:any[]=await new Promise((r,j)=>reader.readEntries(r,j));if(!batch.length)break;out.push(...await readEntries(batch,prefix+entry.name+'/'));}}if(out.length>2048)throw Error('파일은 한 번에 2,048개까지 열 수 있습니다.');}return out;}
function resolvePath(base:string,ref:string){const parts=ref.startsWith('/')?[]:base.split('/').slice(0,-1);for(const part of decodeURIComponent(ref.split(/[?#]/)[0]).replaceAll('\\','/').split('/')){if(part==='..')parts.pop();else if(part&&part!=='.')parts.push(part);}return parts.join('/');}
export async function preparePresentation(files:LocalFile[],entry:string,channel:string){
 const urls:string[]=[],map=new Map(files.map(f=>[f.name,f])),cache=new Map<string,string>(),busy=new Set<string>(),missing=new Set<string>();
 function allocate(text:Blob){const url=URL.createObjectURL(text);urls.push(url);return url;}
 const mime=(name:string)=>/\.css$/i.test(name)?'text/css':/\.(js|mjs)$/i.test(name)?'text/javascript':undefined;
 async function replacement(base:string,ref:string):Promise<string>{if(!ref||/^(?:[a-z][a-z0-9+.-]*:|\/\/|#)/i.test(ref))return ref;const name=resolvePath(base,ref);if(!map.has(name)){missing.add(ref);return ref;}return await asset(name)+(ref.includes('#')?'#'+ref.split('#').slice(1).join('#'):'');}
 async function css(text:string,name:string){const hits=[...text.matchAll(/url\(\s*(['"]?)(.*?)\1\s*\)/g)];for(const hit of hits)text=text.replace(hit[0],`url("${await replacement(name,hit[2])}")`);return text;}
 async function asset(name:string):Promise<string>{if(cache.has(name))return cache.get(name)!;const item=map.get(name)!;if(busy.has(name))throw Error('순환 참조하는 스크립트 파일은 이 버전에서 열 수 없습니다.');busy.add(name);let url;
  if(mime(name)){let text=await item.file.text();if(/\.css$/i.test(name))text=await css(text,name);else{const hits=[...text.matchAll(/((?:from\s*|import\s*\(?\s*)['"])(\.{1,2}\/[^'"]+)(['"])/g)];for(const hit of hits)text=text.replace(hit[0],hit[1]+await replacement(name,hit[2])+hit[3]);}url=allocate(new Blob([text],{type:mime(name)}));}
  else url=allocate(item.file);busy.delete(name);cache.set(name,url);return url;
 }
 try{const raw=await map.get(entry)!.file.text(),doc=new DOMParser().parseFromString(raw,'text/html');doc.querySelectorAll('base').forEach(el=>el.remove());
 for(const el of doc.querySelectorAll('[src],[href],[poster]'))for(const attr of ['src','href','poster'])if(el.hasAttribute(attr))el.setAttribute(attr,await replacement(entry,el.getAttribute(attr)!));
 for(const el of doc.querySelectorAll('style'))el.textContent=await css(el.textContent||'',entry);for(const el of doc.querySelectorAll('[style]'))el.setAttribute('style',await css(el.getAttribute('style')!,entry));
 for(const el of doc.querySelectorAll('[srcset]')){const src=el.getAttribute('srcset')!;if(!src.startsWith('data:')){const parts=[];for(const part of src.split(',')){const [ref,...size]=part.trim().split(/\s+/);parts.push(await replacement(entry,ref)+' '+size.join(' '));}el.setAttribute('srcset',parts.join(', '));}}
 const script=doc.createElement('script');script.textContent='('+bridgeRuntime.toString()+')('+JSON.stringify(channel)+');';doc.head.insertBefore(script,doc.head.firstChild);
 return {html:'<!doctype html>\n'+doc.documentElement.outerHTML,urls,missing:[...missing]};
 }catch(e){urls.forEach(URL.revokeObjectURL);throw e;}
}
// Runs inside an opaque-origin sandbox; no access to the app's cookies or session keys.
function bridgeRuntime(channel:string){
 async function dropped(entries:any[],prefix=''):Promise<any[]>{const files:any[]=[];for(const entry of entries){if(entry.isFile)files.push({name:prefix+entry.name,file:await new Promise((resolve,reject)=>entry.file(resolve,reject))});else{const reader=entry.createReader();for(;;){const batch:any[]=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));if(!batch.length)break;files.push(...await dropped(batch,prefix+entry.name+'/'));}}if(files.length>2048)throw Error('파일은 한 번에 2,048개까지 열 수 있습니다.');}return files;}
 document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();},true);
 document.addEventListener('drop',async e=>{if(!e.dataTransfer?.files.length)return;e.preventDefault();e.stopImmediatePropagation();const entries=Array.from(e.dataTransfer.items).map((item:any)=>item.webkitGetAsEntry?.()).filter(Boolean),fallback=Array.from(e.dataTransfer.files).map(file=>({name:file.name,file}));try{emit('files',{files:entries.length?await dropped(entries):fallback});}catch(error){emit('error',{message:(error as Error).message});}},true);
 const emit=(type:string,data:any={})=>parent.postMessage({channel,type,...data},'*');let x=.5,y=.5,black=false,pointer=false,pick:string|null=null,mapping:any={},saved:any=null,resizing=false,layer:any,shade:any,laser:any;
 function snapshot(){const anchor=document.elementFromPoint(innerWidth*.5,innerHeight*.35);if(!anchor||anchor.closest('[data-sl-effects]'))return saved;let scroller:any=anchor.parentElement;while(scroller&&scroller!==document.body&&!(scroller.scrollHeight>scroller.clientHeight&&/auto|scroll/.test(getComputedStyle(scroller).overflowY)))scroller=scroller.parentElement;if(!scroller||scroller===document.body)scroller=document.scrollingElement;const rect=anchor.getBoundingClientRect();return {anchor,scroller,ratio:rect.height?(innerHeight*.35-rect.top)/rect.height:0,width:innerWidth,height:innerHeight,top:scroller.scrollTop};}
 function restore(){if(!saved?.anchor.isConnected)return;(window as any).Reveal?.layout?.();const rect=saved.anchor.getBoundingClientRect();saved.scroller.scrollTo({top:saved.anchor===document.body?saved.top:saved.scroller.scrollTop+rect.top+rect.height*saved.ratio-innerHeight*.35,behavior:'instant'});}
 function effects(){if(!layer)return;shade.style.display=black?'block':'none';laser.style.display=pointer&&!black?'block':'none';laser.style.left=x*100+'%';laser.style.top=y*100+'%';if(black||pointer){layer.style.display='block';if(layer.showPopover&&!layer.matches(':popover-open'))layer.showPopover();}else{if(layer.matches(':popover-open'))layer.hidePopover();layer.style.display='none';}emit('effects',{black,pointer});}
 function selector(el:Element){if(el.id)return '#'+CSS.escape(el.id);const parts=[];while(el&&el.tagName!=='HTML'){let part=el.tagName.toLowerCase();const peers=el.parentElement?[...el.parentElement.children].filter(p=>p.tagName===el.tagName):[];if(peers.length>1)part+=':nth-of-type('+(peers.indexOf(el)+1)+')';parts.unshift(part);if(!el.parentElement)break;el=el.parentElement;}return parts.join(' > ');}
 function keyboard(key:string){const codes:any={ArrowRight:39,ArrowLeft:37,PageDown:34,PageUp:33,Home:36};for(const type of ['keydown','keyup'])(document.activeElement||document.body).dispatchEvent(new KeyboardEvent(type,{key,code:key,keyCode:codes[key],which:codes[key],bubbles:true,cancelable:true}));}
 addEventListener('message',e=>{if(e.source!==parent||e.data?.channel!==channel)return;const d=e.data;if(typeof d.action!=='string'||d.action.startsWith('document-'))return;try{
  if(d.action==='config'){mapping=d.mapping||{};return;}if(d.action==='snapshot'){saved=snapshot();return;}if(d.action==='pick'){pick=d.which;return;}if(d.action==='cancel-pick'){pick=null;return;}
  if(d.action==='black'){black=!black;effects();return;}if(d.action==='pointer'){pointer=!pointer;effects();return;}if(d.action==='move'){x=d.x;y=d.y;pointer=true;effects();return;}
  const target=document.elementFromPoint(Math.min(innerWidth-1,x*innerWidth),Math.min(innerHeight-1,y*innerHeight)) as HTMLElement;
  if(d.action==='click'){target?.focus?.({preventScroll:true});target?.click?.();return;}if(d.action==='scroll'){let el:any=target;while(el&&el!==document.body&&!(el.scrollHeight>el.clientHeight&&/auto|scroll/.test(getComputedStyle(el).overflowY)))el=el.parentElement;(el&&el!==document.body?el:window).scrollBy({top:d.y,behavior:'smooth'});return;}
  if(mapping[d.action]){const button=document.querySelector(mapping[d.action]) as HTMLElement;if(!button)throw Error('지정한 버튼을 다시 선택해 주세요.');button.click();return;}
  const reveal=(window as any).Reveal;if(reveal?.next){if(d.action==='first')reveal.slide(0,0);else if(d.action==='next')reveal.next();else reveal.prev();return;}
  keyboard(d.action==='first'?'Home':d.action==='next'?(mapping.keys==='pages'?'PageDown':'ArrowRight'):(mapping.keys==='pages'?'PageUp':'ArrowLeft'));
 }catch(error){emit('error',{message:(error as Error).message});}});
 document.addEventListener('click',e=>{if(!pick)return;e.preventDefault();e.stopImmediatePropagation();const target=(e.target as Element).closest('button,a,[role="button"],input')||e.target as Element;emit('mapped',{which:pick,selector:selector(target)});pick=null;},true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pick){pick=null;emit('cancel-pick');}},true);
 document.addEventListener('scroll',()=>{if(!resizing&&(!saved||saved.width===innerWidth&&saved.height===innerHeight))saved=snapshot();},true);
 addEventListener('resize',()=>{resizing=true;requestAnimationFrame(()=>requestAnimationFrame(()=>{restore();resizing=false;saved=snapshot();}));});
 document.addEventListener('fullscreenchange',()=>{effects();emit('fullscreen',{active:!!document.fullscreenElement});});
 const initializeEffects=()=>{layer=document.createElement('div');layer.dataset.slEffects='';layer.setAttribute('popover','manual');layer.style.cssText='all:initial;position:fixed;inset:0;width:100vw;height:100vh;margin:0;padding:0;border:0;background:transparent;pointer-events:none;display:none;z-index:2147483647';shade=document.createElement('div');shade.style.cssText='position:absolute;inset:0;background:black;display:none';laser=document.createElement('div');laser.style.cssText='position:absolute;width:18px;height:18px;border-radius:50%;background:#ff5965;border:2px solid white;box-shadow:0 0 14px #ff5965;transform:translate(-50%,-50%);display:none';layer.append(shade,laser);document.body.append(layer);saved=snapshot();emit('ready');};
 if(document.documentElement.hasAttribute('data-sl-document'))document.addEventListener('sl-document-ready',initializeEffects,{once:true});else addEventListener('load',initializeEffects,{once:true});
}

